name: Deploy Quartz site to Nginx

on:
  push:
    branches:
      - v4

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Create SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > private.key
          sudo chmod 600 private.key
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          ls -alt ./
          ls -alt ../
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/private.key
      - name: "rsync public/ to nginx server"
        run: |
          echo "$SSH_KEY_PATH"
          # rsync -avz -e "ssh -i $SSH_KEY_PATH" public/ brk@172.235.173.145:~/website/
          scp -r -i private.key public/ brk@172.235.173.145:~/website/
